name: Vulnerability Check

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  schedule:
    # Run daily at 2:00 AM UTC
    - cron: "0 2 * * *"

jobs:
  vulncheck:
    name: Run Vulnerability Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25.1"
          check-latest: true

      - name: Install govulncheck
        run: go install golang.org/x/vuln/cmd/govulncheck@latest

      - name: Run vulnerability check
        run: |
          # Also check each module individually to get more detailed output
          echo "Checking individual modules..."
          find . -name "go.mod" -not -path "./vendor/*" | while read -r gomod; do
            dir=$(dirname "$gomod")
            echo "Checking module in $dir"
            cd "$dir"
            govulncheck ./...
            cd - > /dev/null
          done
